interface OwnershipInfoVM {
  Id: number
  /// <summary>
  /// 用户名
  /// </summary>
  UserName: string
  /// <summary>
  /// 名称
  /// </summary>
  Name: string
  /// <summary>
  /// 头像
  /// </summary>
  Header: string
  /// <summary>
  /// guid,唯一id
  /// </summary>
  OwnershipId: string
  /// <summary>
  /// 标题
  /// </summary>
  Title: string
  /// <summary>
  /// 物品类型
  /// </summary>
  ObjectType: number
  /// <summary>
  /// 销售价格
  /// </summary>
  Price: number

  SourceType: number
  /// <summary>
  /// 来源编码
  /// </summary>
  SourceCode: string
  /// <summary>
  /// 获得时间
  /// </summary>
  OwnershipTime: string
  /// <summary>
  /// 备注
  /// </summary>
  Note: string
  Image: string
}
