interface StatisticOverviewVM {
  /// <summary>
  /// 用户数量
  /// </summary>
  UserCount: number
  /// <summary>
  /// 话题数量
  /// </summary>
  ConversationCount: number
  /// <summary>
  /// 聊天数量
  /// </summary>
  ChatCount: number
  /// <summary>
  /// Ai作图数量
  /// </summary>
  AiDrawingCount: number
  /// <summary>
  /// 问答数量
  /// </summary>
  MessageCount: number
  /// <summary>
  /// 点赞数量
  /// </summary>
  LikeCount: number
  /// <summary>
  /// 收藏数量
  /// </summary>
  FavoriteCount: number
  /// <summary>
  /// 浏览数量
  /// </summary>
  ViewCount: number
  /// <summary>
  /// 评论数量
  /// </summary>
  CommentCount: number
  ImageFixCount: number

  /// <summary>
  /// 用户数量
  /// </summary>
  TodayUserCount: number
  /// <summary>
  /// 话题数量
  /// </summary>
  TodayConversationCount: number
  /// <summary>
  /// 聊天数量
  /// </summary>
  TodayChatCount: number
  /// <summary>
  /// Ai作图数量
  /// </summary>
  TodayAiDrawingCount: number
  /// <summary>
  /// 问答数量
  /// </summary>
  TodayMessageCount: number
  /// <summary>
  /// 点赞数量
  /// </summary>
  TodayLikeCount: number
  /// <summary>
  /// 收藏数量
  /// </summary>
  TodayFavoriteCount: number
  /// <summary>
  /// 浏览数量
  /// </summary>
  TodayViewCount: number
  /// <summary>
  /// 评论数量
  /// </summary>
  TodayCommentCount: number
  TodayImageFixCount: number
  /// <summary>
  /// 未审核的话题
  /// </summary>
  UncheckConversationCount: number
  /// <summary>
  /// 未审核的话题
  /// </summary>
  UncheckAiDrawingCount: number
  /// <summary>
  /// 未审核的话题
  /// </summary>
  UncheckCommentCount: number
  /// <summary>
  /// 未审核的话题
  /// </summary>
  UncheckMessageCount: number
  UncheckImageFixCount: number
  TodayNoWatermarkCount: number
  NoWatermarkCount: number
  RemoveBgCount: number
  TodayRemoveBgCount: number
  UncheckRemoveBgCount: number
}
