import { boolean, number, string } from 'yargs'

interface DrawingInfoVM {
  Id: number
  /// <summary>
  /// 用户名
  /// </summary>
  UserName: string
  /// <summary>
  /// 名称
  /// </summary>
  Name: string
  /// <summary>
  /// 头像
  /// </summary>
  Header: string
  /// <summary>
  /// guid,唯一id
  /// </summary>
  DrawingId: string
  /// <summary>
  /// guid,唯一id
  /// </summary>
  ConversationId: string
  /// <summary>
  /// 画图类型
  /// </summary>
  DrawType: number
  /// <summary>
  /// 文本
  /// </summary>
  Prompt: string
  /// <summary>
  /// 文本英文
  /// </summary>
  PromptEn: string
  /// <summary>
  /// 文本英文(消极)
  /// </summary>
  NegativePromptEn: string
  /// <summary>
  /// 风格
  /// </summary>
  Style: string
  /// <summary>
  /// 艺术家
  /// </summary>
  Artist: string
  /// <summary>
  /// 生成的图片宽度
  /// </summary>
  Width: number
  /// <summary>
  /// 生成的图片高度
  /// </summary>
  Height: number
  /// <summary>
  /// 种子
  /// </summary>
  Seed: number
  /// <summary>
  /// 1-30越大代表和训练原图越相似，随机度 默认7
  /// </summary>
  CFG: number
  /// <summary>
  /// 取样方法 默认Euler a
  /// </summary>
  SamplingMethod: number
  /// <summary>
  /// 取样步数量，一般越大细节越多，1-150，推荐20-30
  /// </summary>
  Steps: number
  /// <summary>
  /// 是否重建脸部，突出脸部细节
  /// </summary>
  RestoreFaces: boolean

  /// <summary>
  /// img2img的参数 图片裁剪模式
  /// </summary>
  ResizeMode: string

  /// <summary>
  /// img2img的参数和原图的相识程度
  /// </summary>
  DenoisingStrength: number
  /// <summary>
  /// 图片数量
  /// </summary>
  ImageCount: number

  /// <summary>
  /// 状态
  /// </summary>
  DrawingStatus: number

  /// <summary>
  /// 尺寸放大倍数
  /// </summary>
  Resize: number
  /// <summary>
  /// 模型是否支持中文
  /// </summary>
  SupportChinese: boolean
  /// <summary>
  /// 模型名称
  /// </summary>
  ModelName: string
  /// <summary>
  /// 属性名称
  /// </summary>
  Property: string
  /// <summary>
  /// 比例名称
  /// </summary>
  Ratio: string
  /// <summary>
  /// 点赞数量
  /// </summary>
  Likes: number
  /// <summary>
  /// 评论数量
  /// </summary>
  Comments: number
  /// <summary>
  /// 收藏数量
  /// </summary>
  Favorites: number
  /// <summary>
  /// 浏览次数
  /// </summary>
  Views: number
  ConversationId: string
}
